channels:
- defaults
dependencies:
- python=3.9.5
- scikit-learn=1.0.1
- pip=21.2.4
- pip:
  - numpy==1.23.4
  - housing_value-0.0.0-py3-none-any.whl
  - mlflow==1.23.1
  - cloudpickle==2.0.0
  - typing-extensions==3.10.0.2
  - protobuf==3.20
name: mlflow-env